<?php

/**
 * @file
 * Primarily Drupal hooks and tools for IAAB
 */

function tetraedre_commons_menu() {
  $items['admin/config/tetraedre/settings'] = array(
    'title' => t('Tetraedre settings'),
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tetraedre_commons_settings_form'),
    'access arguments' => array('access administration menu')
  );

  return $items;
}

function tetraedre_commons_init() {
  global $base_url;
  $theme_path = drupal_get_path('theme', 'tetraedre');
  $full_theme_path = $base_url . '/' . $theme_path;
  drupal_add_js(array('tetraedre_commons_base_url' => array('base_url' => $base_url)), 'setting');
  drupal_add_js(array('tetraedre_commons_full_theme_path' => array('full_theme_path' => $full_theme_path)), 'setting');
}

function tetraedre_commons_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'webform_client_form_9') {
    foreach ($form['submitted'] as $key => $element) {
      if ($element['#type'] == 'textfield' || $element['#type'] == 'textarea' || $element['#type'] == 'webform_email') {
        $form['submitted'][$key]['#attributes']['placeholder'] = $element['#title'];
      }
    }
    $form['actions']['submit']['#attributes']['class'] = array('button', 'form');
  }
}

function tetraedre_commons_settings_form() {
  $form = array();

  $form['tetraedre_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Main email for Tetraedre'),
    '#default_value' => variable_get('tetraedre_email', '')
  );

  $form['tetraedre_address'] = array(
    '#type' => 'textfield',
    '#title' => t('Address'),
    '#default_value' => variable_get('tetraedre_address', '')
  );

  $form['tetraedre_city'] = array(
    '#type' => 'textfield',
    '#title' => t('City'),
    '#default_value' => variable_get('tetraedre_city', '')
  );

  $form['tetraedre_cp'] = array(
    '#type' => 'textfield',
    '#title' => t('Postal Code'),
    '#default_value' => variable_get('tetraedre_cp', '')
  );

  $form['tetraedre_phone_1'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone 1'),
    '#default_value' => variable_get('tetraedre_phone_1', '')
  );

  $form['tetraedre_phone_2'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone 2'),
    '#default_value' => variable_get('tetraedre_phone_2', '')
  );

  return system_settings_form($form);
}
